[build]
  # 构建命令（对于纯前端项目，通常不需要构建）
  command = "echo 'No build command needed for static site'"
  
  # 发布目录（当前目录的所有文件）
  publish = "."

[build.environment]
  # Node.js 版本（如果需要）
  NODE_VERSION = "18"

# 重定向规则 - 对于单页应用，所有路由都重定向到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 安全头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com https://js.stripe.com https://cdn.jsdelivr.net https://accounts.google.com https://apis.google.com https://www.googleapis.com; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data: blob: https:; font-src 'self' data: https:; connect-src 'self' https://portal.2brain.ai https://www.googleapis.com https://identitytoolkit.googleapis.com https://securetoken.googleapis.com https://firestore.googleapis.com https://storage.googleapis.com https://analytics.google.com https://www.gstatic.com https://apis.google.com; frame-src 'self' https://accounts.google.com https://js.stripe.com https://test-base-a7c4b.firebaseapp.com;"

# 缓存设置
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 环境变量（如果需要在构建时使用）
# 注意：敏感信息不应该放在这里，应该在 Netlify 控制台中设置
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
